#!/bin/sh
# 
echo
echo "############# System Updates/Upgrades ausführen & Installation der 'unattended_upgrades' ###############"
sudo apt update -y  
sudo apt upgrade -y
sudo apt autoremove -y


echo "############# Zusätzliche Software' ###############"
sudo apt install fish -y
chsh -s /usr/bin/fish 

echo "############# Zusätzliche Software' ###############"

#sudo apt install gparted -y
#sudo apt install synaptic -y
#sudo apt install libreoffice -y
#sudo apt install gnome-disk-utility -y
#sudo apt install nautilus -y
#sudo apt install lshw -y
#sudo apt install curl -y
#sudo apt install wget -y
#sudo apt install xscreensaver -y

echo "############# node red installieren ###############"

#bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
#sudo apt install build-essential git curl -y
#sudo systemctl enable nodered.service
#sudo systemctl restart nodered.service

echo " jetzt auf  http://192.168.178.37:1880 aktiv"

echo "############# InfluxDB installieren ###############"


wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

sudo apt update && sudo apt install -y influxdb

sudo systemctl unmask influxdb.service
sudo systemctl start influxdb
sudo systemctl enable influxdb.service




echo "############# Grafana installieren ###############"

wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

sudo apt update && sudo apt install -y grafana


sudo systemctl unmask grafana-server.service
sudo systemctl start grafana-server
sudo systemctl enable grafana-server.service

echo " jetzt auf  http://192.168.178.37:3000 aktiv"

echo "############# Syncthing installieren ###############"

sudo apt-get install curl
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sour>
sudo apt update && sudo apt install syncthing -y
syncthing

echo "#############               ACHTUNG              ###############"
echo "############# IP Adresse ändern in: 0.0.0.0:8384 ###############"
echo "#############               ACHTUNG              ###############"
nano /home/pi/.config/syncthing/config.xml

sudo systemctl enable syncthing@pi.service
sudo systemctl restart syncthing@pi.service

echo " jetzt auf  http://192.168.178.37:8384 aktiv"


echo "############# MQTT installieren ###############"

sudo apt install mosquitto
sudo apt install mosquitto-clients
sudo systemctl enable mosquitto 
sudo systemctl start mosquitto 
echo "#############  Konfiguration User-Accounts ###############"
echo "#############  siehe hier:  https://plantprogrammer.de/mqtt-auf-dem-raspberry-pi-mosquitto/ ###############"




echo "############# Installation abgeschlossen, das System wird neu gestartet ###############"
sudo reboot 
