#!/bin/sh
# 
echo
echo "############# System Updates/Upgrades ausführen & Installation der 'unattended_upgrades' ###############"
sudo apt update -y  
sudo apt upgrade -y
sudo apt autoremove -y


echo "############# Zusätzliche Software' ###############"
sudo apt install fish -y


echo "############# Zusätzliche Software' ###############"

#sudo apt install gparted -y
#sudo apt install synaptic -y
#sudo apt install libreoffice -y
#sudo apt install gnome-disk-utility -y
#sudo apt install nautilus -y
#sudo apt install lshw -y
#sudo apt install curl -y
#sudo apt install wget -y
#sudo apt install xscreensaver -y
sudo apt install build-essential git curl


echo "############# InfluxDB installieren ###############"


wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

sudo apt update && sudo apt install -y influxdb

sudo systemctl unmask influxdb.service
sudo systemctl start influxdb
sudo systemctl enable influxdb.service




echo "############# Grafana installieren ###############"

wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

sudo apt update && sudo apt install -y grafana


sudo systemctl unmask grafana-server.service
sudo systemctl start grafana-server
sudo systemctl enable grafana-server.service

echo " jetzt auf  http://192.168.178.37:3000 aktiv"

echo "############# Syncthing installieren ###############"

sudo apt install curl -y
sudo curl -s -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
sudo apt update -y
sudo apt install syncthing -y






echo "############# MQTT installieren ###############"

sudo apt install mosquitto -y
sudo apt install mosquitto-clients -y
sudo systemctl enable mosquitto 
sudo systemctl start mosquitto 
echo "#############  Konfiguration User-Accounts ###############"
echo "#############  siehe hier:  https://plantprogrammer.de/mqtt-auf-dem-raspberry-pi-mosquitto/ ###############"


echo "############# Node Red installieren ###############"

echo "############# #bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)"
/bin/bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) 
node-red-start
sudo systemctl enable nodered.service
sudo systemctl restart nodered.service


echo " jetzt auf  http://192.168.178.37:1880 aktiv"

echo "############# NginX installieren ###############"
sudo apt install nginx -y
sudo systemctl start nginx


echo "#############               ACHTUNG              ###############"
echo "############# nach der Installation und dem Reboot müssen noch folgende Punkte durchgeführt werden"
 
echo "############# Syncthing muss als Programm ausgeführt werden und anschließen konfiguriert werden ###############"
echo "############# IP Adresse ändern in: 0.0.0.0:8384 ###############"
echo "############# Folgendes Vorgehen ###############"
echo "# syncthing"
echo "# nano /home/pi/.config/syncthing/config.xml"
echo "# sudo systemctl enable syncthing@pi.service"
echo "# sudo systemctl restart syncthing@pi.service"
echo "# echo " jetzt auf  http://192.168.178.37:8384 aktiv"

echo "#############               fish als Shell aktivieren              ###############"
echo "#  chsh -s /usr/bin/fish "



echo "#############             WEITER MIT <ENTER>             ###############"
read answer

echo "############# Installation abgeschlossen, das System wird neu gestartet ###############"
sudo reboot 

